CREATE DATABASE EduHome
USE EduHome

CREATE TABLE Events
(
Id INT PRIMARY KEY IDENTITY,
Name NVARCHAR(100) NOT NULL,
Descrp NVARCHAR(100),
Adress NVARCHAR(100),
StartDate DATE,
StartTime TIME,
EndTime TIME
)
SELECT * FROM Events

CREATE TABLE Speakers
(
Id INT PRIMARY KEY IDENTITY,
FullName NVARCHAR(100) NOT NULL,
Position NVARCHAR(100),
Company NVARCHAR(100),
ImageUrl NVARCHAR(150)
)
SELECT * FROM Speakers

CREATE TABLE EventSpeakers
(
EventId INT FOREIGN KEY REFERENCES Events(Id),
SpeakerId INT FOREIGN KEY REFERENCES Speakers(Id)
)
SELECT * FROM EventSpeakers